/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package varios;

/**
 *
 * @author Asus
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnVentanaCircunferencia = new javax.swing.JButton();
        bntVentanaCuadrado = new javax.swing.JButton();
        btnElipse = new javax.swing.JButton();
        btnRectangulo = new javax.swing.JButton();
        btnRecta = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Figuras Geométicas");

        lblTitulo.setText("FIGURAS GEOMÉTRICAS");

        btnVentanaCircunferencia.setText("CIRCUNFERENCIA");
        btnVentanaCircunferencia.setMaximumSize(new java.awt.Dimension(70, 20));
        btnVentanaCircunferencia.setMinimumSize(new java.awt.Dimension(70, 20));
        btnVentanaCircunferencia.setPreferredSize(new java.awt.Dimension(70, 20));
        btnVentanaCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaCircunferenciaActionPerformed(evt);
            }
        });

        bntVentanaCuadrado.setText("CUADRADO");
        bntVentanaCuadrado.setToolTipText("");
        bntVentanaCuadrado.setMaximumSize(new java.awt.Dimension(70, 20));
        bntVentanaCuadrado.setMinimumSize(new java.awt.Dimension(70, 20));
        bntVentanaCuadrado.setPreferredSize(new java.awt.Dimension(70, 20));
        bntVentanaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVentanaCuadradoActionPerformed(evt);
            }
        });

        btnElipse.setText("ELIPSE");
        btnElipse.setMaximumSize(new java.awt.Dimension(70, 20));
        btnElipse.setMinimumSize(new java.awt.Dimension(70, 20));
        btnElipse.setPreferredSize(new java.awt.Dimension(70, 20));
        btnElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElipseActionPerformed(evt);
            }
        });

        btnRectangulo.setText("RECTANGULO");
        btnRectangulo.setMaximumSize(new java.awt.Dimension(70, 20));
        btnRectangulo.setMinimumSize(new java.awt.Dimension(70, 20));
        btnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloActionPerformed(evt);
            }
        });

        btnRecta.setText("SEGMENTO DE RECTA");
        btnRecta.setMaximumSize(new java.awt.Dimension(70, 20));
        btnRecta.setMinimumSize(new java.awt.Dimension(70, 20));
        btnRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectaActionPerformed(evt);
            }
        });

        btnTriangulo.setText("TRIANGULO");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVentanaCircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecta, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(bntVentanaCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVentanaCircunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntVentanaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaCircunferenciaActionPerformed
        // TODO add your handling code here:
        if(vc == null) vc = new VentanaCircunferencia();
        
        vc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVentanaCircunferenciaActionPerformed

    private void bntVentanaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVentanaCuadradoActionPerformed
        // TODO add your handling code here:
        if(vcua == null) vcua = new VentanaCuadrado();
        
        vcua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVentanaCuadradoActionPerformed

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        // TODO add your handling code here:
        if(vrec == null) vrec= new VentanaRectangulo();
        
        vrec.setVisible(true);
        //this.dispose();
        
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElipseActionPerformed
        // TODO add your handling code here:
        if(veli == null) veli = new VentanaElipse();
        veli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnElipseActionPerformed

    private void btnRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectaActionPerformed
        // TODO add your handling code here:
        if(vseg == null) vseg = new VentanaSegmento();
        vseg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRectaActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        // TODO add your handling code here:
        if(vtri == null) vtri = new VentanaTriangulo();
        vtri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Formulario().setVisible(true);
//            }
//        });
//    }
    
    //Mis Atributos
    VentanaCircunferencia vc;
    VentanaCuadrado vcua; 
    VentanaRectangulo vrec; 
    VentanaElipse veli;  
    VentanaSegmento vseg; 
    VentanaTriangulo vtri;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVentanaCuadrado;
    private javax.swing.JButton btnElipse;
    private javax.swing.JButton btnRecta;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JButton btnVentanaCircunferencia;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
